### ISSUE TITLE
Getting `Unsupported engine` using `npm install`

### ISSUE THREAD

**Issue by evangalen** [pashak09/eslint-plugin-ts-expect-error-validator#4]
First of all I would like to say that your ESLint plugin looks very useful.

Enforcing usage of `// @ts-expect-error` (instead of `// @ts-ignore`) combined why TS error code and error description,
is the only way that should allow to (temporary) suppress a TS error.

Even-though your ESLint plugin looks quite useful, I decide for the moment to use against it.
This because I get an `Unsupported engine` when I `npm install` it

```
$ npm install eslint-plugin-ts-expect-error-validator --save-dev
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'eslint-plugin-ts-expect-error-validator@0.0.3',
npm WARN EBADENGINE   required: { node: '>=16', npm: 'please-use-yarn', yarn: '^1.22.5' },
npm WARN EBADENGINE   current: { node: 'v18.16.1', npm: '9.5.1' }
npm WARN EBADENGINE }
```

Why the explicit requirement for using Yarn (besides personal preference)?
Would it be possible to remove the `"npm": "please-use-yarn"` from the `"engines"` section?

**Comment by pashak09** [comment]
Thanks for your contribution. Updated
